# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'GluedInExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GluedInExample
pod 'GluedInSDK', "2.4.6"
 pod 'SkeletonView'
end
